### ISSUE TITLE
Замечания к работе @katok-tv

### ISSUE THREAD

**Issue by ananasn** [fop2020/lab1#4]
Есть несколько замечаний к вашей работе, @katok-tv.
* Объясните зачем вы используте модуль csv и затем обратно все объединяете в строку (через join)? 
Идти по строчкам можно и без этого модуля `for line in f:`.
* В Python не называют переменные  в kebabCase, нужно использовать snake_case.
* Ознакомьтесь со стандратом [PEP8](https://www.python.org/dev/peps/pep-0008/), в котором даются указания по оформлению кода на языке Python.

**Comment by katok-tv** [comment]
> Есть несколько замечаний к вашей работе, @katok-tv.
> 
> * Объясните зачем вы используте модуль csv и затем обратно все объединяете в строку (через join)?
>   Идти по строчкам можно и без этого модуля `for line in f:`.
> * В Python не называют переменные  в kebabCase, нужно использовать snake_case.
> * Ознакомьтесь со стандратом [PEP8](https://www.python.org/dev/peps/pep-0008/), в котором даются указания по оформлению кода на языке Python.

Я сделала так, потому что обработка исходного файла при помощи модуля csv и дальнейшая склейка через join в одну строку позволяет убрать случаи, когда предложение разбивается на несколько строк

**Comment by ananasn** [comment]
Засчет чего это происходит? Приведите пример файла и кода когда результат меняется

**Comment by katok-tv** [comment]
> Засчет чего это происходит? Приведите пример файла и кода в когда результат меняется

 Если брать тот же файл, который я обрабатывала в лабораторной работе, то вот 2 скрина обработки без join и с ним. Как видно, с Join символов больше находит. 
![image](https://user-images.githubusercontent.com/70949435/95500095-f8

**Comment by katok-tv** [comment]
> Засчет чего это происходит? Приведите пример файла и кода когда результат меняется

Например, для того же файла, который я обрабатывала в лабораторной, двумя способами выводится разный результат, причём с использованием join символов получается больше. Вот ссылка на гугл диск со скринамиhttps://drive.google.com/drive/folders/1M42dLspsI7WTK5CLvMzmERBWE0Ioy-kE?usp=sharing

**Comment by ananasn** [comment]
Да, я запускала ваш код и видела это.
Как раз в этом и проблема :)
Возьмите какой-то пример попроще и короче именно показательный для описанного в первом ответе вами случая.

**Comment by ananasn** [comment]
Рекомендую все таки ознакомиться с тем, что такое csv файл, и какую роль там выполняют запятые.
И еще методом rstrip() -- он убирает пробельные (\n \t  ) символы в конце строки. Для того, чтобы просто избавиться от символа новой строки, не стоит подключать целый модуль csv. Тем более потом, вы всю работу модуля csv по разбиению файла по разделителям обнуляете через join, который является достаточно дорогостоящей операцией.

А чтобы избавляться от кавычек в начале строкового литерала можно делать так line.strip('"')
Или, если кавычки внутри строки, то можно просто посчитать количество кавычек line.count('"') и вычесть из искомого.

В идеале, конечно, ваша программа не должна учитывать запятые-разделители. Вот тут уж модуль csv может пригодиться. Логичнее всего было бы итерироваться по ячейкам таблицы в каждой строке и анализировать каждую отдельную ячейку.
