### ISSUE TITLE
Недочеты по лабораторной работе @sohazasoha

### ISSUE THREAD

**Issue by ananasn** [fop2020/lab1#5]
Недочеты по лабораторной работе @sohazasoha:
* Ознакомьтесь со стандратом [PEP8](https://www.python.org/dev/peps/pep-0008/), в котором даются указания по оформлению кода на языке Python.
* `import`  пердпотительно делать в самом начале файла, плюс от импортов делается отступ в две пустые строки (читайте PEP8)
* Называть имена переменных транслитом не нужно, используйте английский язык.
* Объясните зачем вы используте модуль csv и затем обратно все объединяете в строку (через join)?
Идти по строчкам можно и без этого модуля `for line in f:`. Рекомендую все таки ознакомиться с тем, что такое csv файл, и какую роль там выполняют запятые. В идеале, конечно, ваша программа не должна учитывать запятые-разделители. Вот тут уж модуль csv может пригодиться. Логичнее всего было бы итерироваться по ячейкам таблицы в каждой строке и анализировать каждую отдельную ячейку.
* Вам не нужно получать индекс каждого элемента через `range(len(s))`, чтобы затем получить элемент по индексу `s[i]`. Делайте просто `for element in s:`.
* Вот так `if s[i]=='.' or s[i]=='!' or s[i]=='?':` в Python не делают, потому что это отрицательно влияет на читаемость кода. То же самое можно сделать с помощью `in`, например `if element in '.!?' :`

**Comment by ananasn** [comment]
* Не запускается
* Слишком много пустых строк, еще раз прочитайте PEP8
* Рекомендуется использовать для строк одинарные кавычки `'`, двойные кавычки могут понадобиться только в том случае, если они обрамляют одинарные. Или хотя бы используйте либо одинарные, либо двойные, не смешивая.

**Comment by ananasn** [comment]
* Неверный результат. Проверьте на простом файле, например с предложением `Look, you got wrong result. Check code.` У вас выводит:
```
Количество символов без пробелов: 33
Количество символов без знаков препинания: 36
Количество слов: 7
Количество предложений: 1
```
* Ознакомьтесь с [приоритетами операций](https://docs.python.org/3/reference/expressions.html#operator-precedence). Тут явно что-то не то `if '.' or '!' or '?' in s:`
* Слишком много пустых строк, еще раз прочитайте PEP8.
* `s.count(',')+s.count('"')+s.count('-')+s.count('.')` -- не по PEP8

**Comment by sohazasoha** [comment]
Исправила

**Comment by sohazasoha** [comment]
https://github.com/sohazasoha/lab1
