### ISSUE TITLE
Замечания к лабораторной работе @letrongminh the_first_way.py 

### ISSUE THREAD

**Issue by ananasn** [fop2020/lab1#7]
@letrongminh  Проверила вот это файл the_first_way.py 

* Ознакомьтесь со стандратом [PEP8](https://www.python.org/dev/peps/pep-0008/), в котором даются указания по оформлению кода на языке Python.

* Все `import`  предпочтительно делать в самом начале файла, от импортов делается отступ в две пустые строки (читайте PEP8)

* Необязательно использовать `import csv`. Вы можете итерироваться по строчкам без его помощи, следующим образом`for line in f:`

* Перед объявлением функции должно быть две пустых строчки. (PEP8)

* Слишком длинная строчка ```punctuation_marks += characters.count(".") + characters.count(",") + characters.count("?")...```
В соответствии с PEP8 строчка должна быть не больше 79 символов

Исправьте, пожалуйста! :)

**Comment by letrongminh** [comment]
Я исправил
Вы смотрите и комментируете. 
здесь я все еще использую " import csv ", в следующем квесте я буду использовать for line in f:
Этот метод в порядке?

**Comment by ananasn** [comment]
Есть еще небольшое замечание.
Для названия функций и переменных нужно использовать `snake_case` (PEP8). Вместо `getCSV` должно быть `get_csv` и вместо `browseButton_CSV` должно быть `browse_button_csv`.

**Comment by letrongminh** [comment]
Я исправил.
Вы смотрите и комментируете.

**Comment by ananasn** [comment]
Отлично, 10 баллов!
